// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX4Y9y9dddDkcwWdYQ1MV_2XgeD2HYe9c',
    appId: '1:918486127750:web:840640791a647e553eed07',
    messagingSenderId: '918486127750',
    projectId: 'chat-app-f4024',
    authDomain: 'chat-app-f4024.firebaseapp.com',
    storageBucket: 'chat-app-f4024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFPHNX0VbCPK5VnLIo5KmepSF9jUXj69M',
    appId: '1:918486127750:android:43c4fbc4672cc8a03eed07',
    messagingSenderId: '918486127750',
    projectId: 'chat-app-f4024',
    storageBucket: 'chat-app-f4024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpbrWkBJ_J629kYc_WuysRnHtVkVPLJGs',
    appId: '1:918486127750:ios:fc484de899bab77c3eed07',
    messagingSenderId: '918486127750',
    projectId: 'chat-app-f4024',
    storageBucket: 'chat-app-f4024.appspot.com',
    iosClientId: '918486127750-eavcvrmq7th5vk7o8pdihl260ioa0cah.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpbrWkBJ_J629kYc_WuysRnHtVkVPLJGs',
    appId: '1:918486127750:ios:53e6a5a94606a9bd3eed07',
    messagingSenderId: '918486127750',
    projectId: 'chat-app-f4024',
    storageBucket: 'chat-app-f4024.appspot.com',
    iosClientId: '918486127750-vd75pblm7gjk88cbj5vdfi634f5ahsiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
